name: helloGithubAction

on: [push]
permissions: read-all|write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: 1. pip upgrade
      run: python -m pip install --upgrade pip
    - name: 2. 필요한 패키지 인스톨
      run: pip install -r requirements.txt
    - name: 3. 파이썬 실행 
      run: python test.py
    - name: Commit files
      run: |
        git config --local user.email "joosung80@gmail.com"
        git config --local user.name "Joosung Jin[bot]"
        git add .
        git commit -m "Run crawler and update current data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
